apiVersion: v1
kind: Secret
metadata:
  name: build-pass
  annotations:
    tekton.dev/docker-0: https://docker.io # Described below
type: kubernetes.io/basic-auth
stringData:
  username: pfruth
  password: 1916ac0c-2109-47cd-89c6-04eb777cecb2
