apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: modresorts
spec:
  applicationImage: ''
  pullPolicy: Always
  service:
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: modresorts-tls
    certificateSecretRef: modresorts-tls
    port: 9443
  expose: true
  route:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  envFrom:
  - configMapRef:
      name: modresorts-config
  monitoring:
    endpoints:
      - basicAuth:
          password:
            key: password
            name: liberty-creds
          username:
            key: username
            name: liberty-creds
        interval: 5s
        scheme: HTTPS
        tlsConfig:
          insecureSkipVerify: true
    labels:
      app-monitoring: 'true'